_target_: eztorch.models.trunks.create_video_head_model
_recursive_: False
model:
  _target_: eztorch.models.trunks.create_resnet3d_basic
  head: null
  model_depth: 18
head:
  _target_: eztorch.models.heads.create_video_resnet_head
  activation: null
  dropout_rate: 0.
  in_features: 512
  num_classes: 0
  output_size: [1, 1, 1]
  output_with_global_average: true
  pool: null
  pool_kernel_size: [16, 7, 7]
