defaults:
  - /callback/model_checkpoint@callbacks.model_checkpoint: epoch
  - /callback/learning_rate_monitor@callbacks.learning_rate_monitor: default
  - /callback/progress_bar@callbacks.progress_bar: default
  - /datamodule: soccernet
  - /model/finetuning/action_spotting@model: viswin_tiny
  - /transform/soccernet@model.train_transform: resize_mixup_color_jittering_blur_reduce_timestamps
  - /transform/soccernet@model.val_transform: resize_normalize_reduce_timestamps
  - /transform/soccernet@model.test_transform: resize_normalize_reduce_timestamps
  - /optimizer/factory/adamw@model.optimizer: default
  - /scheduler/factory/linear_warmup_cosine_annealing_lr@model.optimizer.scheduler: default
  - /seed/seed_everything@seed: default
  - /trainer: gpu_ddp_amp
  - _self_

callbacks:
  model_checkpoint:
    dirpath: checkpoints
    every_n_epochs: 10
    filename: '{epoch}'
    save_last: True
    save_top_k: 1
    monitor: tight_Average_mAP/mAP
    mode: max
  progress_bar:
    refresh_rate: 50
ckpt_path: null
datamodule:
  datadir: ${..dir.data}
  train:
    decoder_args:
      fps: 2
    dataset:
      label_args:
        cache_dir: ???
        radius_label: 0.5
    clip_sampler:
        _target_: eztorch.datasets.clip_samplers.soccernet.UniformWindowWithoutOverlapSoccerNetClipSampler
        window_duration: 64.
        windows_per_video: 50
        sample_edges: True
        prevent_resample_edges: True
        shuffle: True
    loader:
      drop_last: True
      num_workers: 8
      pin_memory: True
      shuffle: False
    global_batch_size: 64
    transform: null
  val:
    decoder_args:
      fps: 2
    clip_sampler:
        _target_: eztorch.datasets.clip_samplers.soccernet.SlidingWindowSoccerNetClipSampler
        window_duration: 64.
        overlap_window: 32
        shuffle: True
    loader:
      drop_last: False
      num_workers: 8
      pin_memory: True
      shuffle: False
    global_batch_size: 64
    transform: null
  test:
    decoder_args:
      fps: 2
    clip_sampler:
      _target_: eztorch.datasets.clip_samplers.soccernet.SlidingWindowSoccerNetClipSampler
      window_duration: 64.
      overlap_window: 32
      shuffle: True
    loader:
      drop_last: False
      num_workers: 8
      pin_memory: True
      shuffle: False
    transform: null
    global_batch_size: 64
model:
  trunk:
    transformer:
      num_frames: 128
      img_size: 224
  optimizer:
    batch_size: ${...datamodule.train.global_batch_size}
    keys_without_decay: [pos_embed, spatial_cls_token, temporal_cls_token, time_embed, temporal_mask_token]
    exclude_wd_norm: True
    exclude_wd_bias: True
    params:
      weight_decay: 0.05
    initial_lr: 0.001
    scaler: linear
    scheduler:
      interval: step
      params:
        eta_min: 0.00001
        max_epochs: ${.....trainer.max_epochs}
        warmup_epochs: 0
        warmup_start_lr: 0.00001
  evaluation_args:
    split: valid
  prediction_args:
    remove_inference_prediction_seconds: 12
  loss_fn_args:
    class_weights:
      type: null
seed:
  seed: 42
trainer:
  max_epochs: 20
  devices: auto
  check_val_every_n_epoch: 10
  use_distributed_sampler: False
  gradient_clip_val: 1
dir:
  data: data/
  root: outputs/moco
  exp: action_spotting
  run: ${.root}/${.exp}
hydra:
  searchpath:
    - pkg://eztorch.configs
  run:
    dir: ${...dir.run}
