_target_: torchaug.batch_transforms.BatchVideoWrapper
same_on_frames: True
video_format: CTHW
inplace: True
transforms:
- _target_: eztorch.transforms.Div255Input
  inplace: True
- _target_: torchaug.batch_transforms.BatchRandomColorJitter
  brightness: 0.4
  contrast: 0.4
  hue: 0.1
  p: 0.8
  saturation: 0.4
  inplace: True
- _target_: torchaug.batch_transforms.BatchRandomGrayscale
  p: 0.2
  inplace: True
- _target_: torchaug.batch_transforms.BatchRandomHorizontalFlip
  p: 0.5
  inplace: True
- _target_: torchaug.transforms.Normalize
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
  inplace: True
