_target_: eztorch.datamodules.Hmdb51DataModule
_recursive_: False
datadir: ???
train: ???
val: ???
test: ???
video_path_prefix: ${.datadir}
split_id: 1
decode_audio: False
decoder: frame
decoder_args:
  fps: 30
  frame_filter:
    subsample_type: uniform
    num_samples: 8
  time_difference_prob: 0.
  num_threads_io: 4
  num_threads_decode: 4
  decode_float: True
