_target_: eztorch.models.siamese.SCEModel
_recursive_: False
coeff: 0.5
final_scheduler_coeff: 0.
initial_momentum: 0.999
mutual_pass: False
normalize_outputs: True
num_devices: 1
num_global_crops: 2
num_local_crops: 0
num_splits: 0
num_splits_per_combination: 2
optimizer: ???
predictor: null
projector: null
queue: ???
scheduler_coeff: null
scheduler_momentum: constant
simulate_n_devices: 8
shuffle_bn: True
start_warmup_coeff: 1.
sym: False
temp: 0.1
temp_m: 0.04
trunk: ???
use_keys: False
warmup_epoch_coeff: 0
warmup_epoch_temp_m: 0
warmup_scheduler_coeff: linear
warmup_scheduler_temp_m: cosine
