_target_: eztorch.models.heads.create_video_resnet_head
activation: null
dropout_rate: 0.
in_features: 512
num_classes: 101
output_size: [1, 1, 1]
output_with_global_average: true
pool: adaptive_avg_pool_3d
pool_kernel_size: [8, 7, 7]
