_target_: torchvision.transforms.Compose
_recursive_: True
transforms:
- _target_: torchvision.transforms.Resize
  size: 256
- _target_: torchvision.transforms.CenterCrop
  size: 224
- _target_: torchvision.transforms.PILToTensor
