_target_: torchaug.batch_transforms.BatchVideoWrapper
same_on_frames: True
video_format: CTHW
inplace: True
transforms:
- _target_: eztorch.transforms.Div255Input
  inplace: True
- _target_: torchaug.transforms.Normalize
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
  inplace: True
