_target_: eztorch.transforms.OnlyInputTransformWithDictTransform
_recursive_: True
transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: pytorchvideo.transforms.UniformTemporalSubsample
    num_samples: 16
  - _target_: pytorchvideo.transforms.ShortSideScale
    size: 128
dict_transform:
  _target_: pytorchvideo.transforms.UniformCropVideo
  size: 128
  video_key: input
