_target_: eztorch.transforms.OnlyInputTransform
_recursive_: True
transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: pytorchvideo.transforms.UniformTemporalSubsample
    num_samples: 16
  - _target_: pytorchvideo.transforms.ShortSideScale
    size: 112
  - _target_: torchvision.transforms.CenterCrop
    size: 112
