_target_: eztorch.schedulers.scheduler_factory
_recursive_: False
name: linear_warmup_cosine_annealing_lr
params:
  max_epochs: ???
  warmup_epochs: ???
  warmup_start_lr: 0.
  eta_min: 0.
interval: step
