_target_: eztorch.models.siamese.ReSSLModel
_recursive_: False
initial_momentum: 0.999
mutual_pass: False
normalize_outputs: True
num_devices: 1
num_global_crops: 2
num_local_crops: 0
num_splits: 0
num_splits_per_combination: 2
optimizer: ???
predictor: null
projector: null
queue: ???
scheduler_momentum: constant
simulate_n_devices: 8
shuffle_bn: True
sym: False
temp: 0.1
temp_m: 0.04
trunk: ???
use_keys: False
