_target_: eztorch.models.siamese.SCETokensModel
_recursive_: False
coeff: 0.5
final_scheduler_coeff: 0.
initial_momentum: 0.999
keep_aligned_positive: True
mutual_pass: False
normalize_outputs: True
normalize_positive_coeff: False
num_global_crops: 2
num_local_crops: 0
num_prefix_tokens: 0
num_out_tokens: 32
optimizer: ???
positive_radius: 0
predictor: null
projector: null
queue: ???
scheduler_coeff: null
scheduler_momentum: constant
start_warmup_coeff: 1.
sym: False
temp: 0.1
temp_m: 0.05
trunk: ???
use_keys: True
use_all_keys: False
warmup_epoch_coeff: 0
warmup_epoch_temp_m: 0
warmup_scheduler_coeff: linear
warmup_scheduler_temp_m: cosine
