_target_: eztorch.transforms.OnlyInputListTransform
_recursive_: True
transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: eztorch.transforms.RandomTemporalDifference
    absolute: False
    use_grayscale: True
    p: 0.2
  - _target_: pytorchvideo.transforms.UniformTemporalSubsample
    num_samples: 8
  - _target_: eztorch.transforms.video.RandomResizedCrop
    target_height: 224
    target_width: 224
    scale: [0.2, 0.766]
    aspect_ratio: [0.75, 1.3333]
    interpolation: bilinear
