defaults:
  - /callback/model_checkpoint@callbacks.model_checkpoint: epoch
  - /callback/online_evaluator@callbacks.online_evaluator: adam_online_evaluator
  - /model/head/linear@callbacks.online_evaluator.classifier: in512_out200
  - /callback/learning_rate_monitor@callbacks.learning_rate_monitor: default
  - /callback/progress_bar@callbacks.progress_bar: default
  - /datamodule: kinetics200_frame
  - /transform/crops@datamodule.train.transform: kinetics_frame
  - /transform/contrastive@model.train_transform: kinetics_sce
  - /transform/linear_classifier_transform/val@datamodule.val.transform: kinetics_frame_val_cpu
  - /transform/linear_classifier_transform/val@model.val_transform: kinetics_gpu
  - /model/siamese/sce@model: default
  - /model/head/mlp@model.projector: projector_resnet18_mlp3_bn3
  - /model/head/mlp@model.predictor: predictor_resnet18_mlp2_bn1
  - /model/trunk/resnet3d/resnet3d18@model.trunk: no_fc
  - /optimizer/factory/lars@model.optimizer: default
  - /scheduler/factory/linear_warmup_cosine_annealing_lr@model.optimizer.scheduler: default
  - /seed/seed_everything@seed: default
  - /trainer: gpu_ddp_sbn_amp
  - _self_

callbacks:
  model_checkpoint:
    dirpath: pretrain_checkpoints
    every_n_epochs: 100
    filename: '{epoch}'
    save_last: False
    save_top_k: -1
  online_evaluator:
    input_name: h
    optimizer:
      batch_size: ${....datamodule.train.global_batch_size}
    precision: ${...trainer.precision}
  progress_bar:
    refresh_rate: 50
ckpt_path: null
datamodule:
  decoder_args:
    frame_filter:
      subsample_type: uniform
      num_samples: 8
  datadir: ${..dir.data}
  train:
    clip_sampler:
      _target_: eztorch.datasets.clip_samplers.RandomMultiClipSampler
      num_clips: 2
      clip_duration: 2.56
      speeds: [1]
      jitter_factor: 0
    loader:
      drop_last: True
      num_workers: 3
      pin_memory: True
    global_batch_size: 512
  val:
    clip_sampler:
      _target_: eztorch.datasets.clip_samplers.RandomClipSampler
      clip_duration: 2.56
    loader:
      drop_last: False
      num_workers: 3
      pin_memory: True
    global_batch_size: 512
model:
  coeff: 0.5
  queue:
    size: 32768
    feature_dim: ${..projector.output_dim}
  optimizer:
    batch_size: ${...datamodule.train.global_batch_size}
    exclude_wd_norm: False
    exclude_wd_bias: False
    params:
      momentum: 0.9
      weight_decay: 1e-6
    initial_lr: 2.4
    scaler: linear
    scheduler:
      params:
        max_epochs: ${.....trainer.max_epochs}
        warmup_epochs: 35
  projector:
    input_dim: 512
    hidden_dims: [1024, 1024]
    output_dim: 256
  predictor:
    input_dim: 256
    hidden_dims: [1024]
    output_dim: 256
  initial_momentum: 0.99
  scheduler_momentum: cosine
  num_devices: ${..trainer.devices}
  shuffle_bn: False
  simulate_n_devices: 8
  temp: 0.1
  temp_m: 0.07
  sym: True
seed:
  seed: 42
trainer:
  max_epochs: 200
  devices: 8
dir:
  data: data/
  root: outputs/moco
  exp: pretrain_batch_size${..datamodule.train.global_batch_size}_epoch${..trainer.max_epochs}_temp${..model.temp}_seed${..seed.seed}/pretrain
  run: ${.root}/${.exp}

hydra:
  searchpath:
    - pkg://eztorch.configs
  run:
    dir: ${...dir.run}
