_target_: eztorch.models.trunks.create_vit_tiny
img_size: 224
patch_size: 16
in_chans: 3
mlp_ratio: 4
qkv_bias: True
init_values: null
class_token: True
no_embed_class: False
pre_norm: False
drop_rate: 0
attn_drop_rate: 0
drop_path_rate: 0.1
embed_layer: null
norm_layer: null
act_layer: null
block_fn: null
pretrain_pth: null
conv_type: Conv2d
tube_size: 2
